(Mendel ABS with HBP and stepper extruderm skeinforge profile)
(beginning of start.txt)
M104 S225 T0 (Extruder Temperature to 225 Celsius)
M109 S102 T0 (Heated Platform Temperature to 102 Celsius)
G21 (Metric FTW)
G90 (Absolute Positioning)
(You have failed me for the last time, MakerBot)
M6 T0 (Wait for tool to heat up)
(end of start.txt)

